### ISSUE TITLE
Warning while using compute_features

### ISSUE THREAD

**Issue by ShuangquanFeng** [bycycle-tools/bycycle#42] opened 2020-02-28 23:16 UTC
c:\users\shuan\appdata\local\programs\python\python37-32\lib\site-packages\numpy\core\fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
c:\users\shuan\appdata\local\programs\python\python37-32\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount

I encountered this warning sometimes while using compute_features. Is that normal?

**Comment by ryanhammonds** [comment] 2020-05-29 02:17
Hi @ShuangquanFeng, I was able to reproduce this warning when running the unit test for `bycycle.burst.detect_bursts_cycles` and traced it back to the *monotonicity* calculation. The warning is caused by a short (length = 1) rise or decay period. In other words, when an adjacent peak/trough are separate by one sample.

The results is a nan value in the *monotonicity*  column of the dataframe output from `compute_features` and can safely be ignored.

**Comment by ryanhammonds** [comment] 2020-09-29 20:45
This should be resolved as #67 has been merged in. @ShuangquanFeng please reopen if this warning persists when using master, thanks!

**Closed by ryanhammonds** 2020-09-29 20:45 UTC
Labels: question
